const fs=require('fs'),assert=require('node:assert/strict');
const {JSDOM}=require(process.env.PEAR_TEST_MODULES?process.env.PEAR_TEST_MODULES+'/jsdom':'jsdom'),{indexedDB}=require(process.env.PEAR_TEST_MODULES?process.env.PEAR_TEST_MODULES+'/fake-indexeddb':'fake-indexeddb');
(async()=>{
 const old=await new Promise((resolve,reject)=>{const r=indexedDB.open('pear-nai-migration-test',2);r.onupgradeneeded=()=>{for(const n of ['images','vibes','vault'])r.result.createObjectStore(n,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=reject;});
 await new Promise(resolve=>{const tx=old.transaction('images','readwrite');tx.objectStore('images').put({id:'retained',time:1,image:'data:image/png;base64,iVBORw0KGgo='});tx.oncomplete=resolve;});old.close();
 const dom=new JSDOM('<main id="startup"></main>',{url:'https://li-paint.pages.dev',runScripts:'outside-only'}),W=dom.window;
 Object.assign(W,{indexedDB,structuredClone,TextDecoder,TextEncoder,Response,Blob,DecompressionStream,fetch:async()=>{throw Error('Network disabled');}});W.HTMLElement.prototype.scrollIntoView=function(){};
 W.localStorage.setItem('pear-atelier-state',JSON.stringify({pear_nai_studio:{scope:'migration-test',settings:{}}}));
 for(const p of ['dist/settings-backup.js','dist/themes.js'])W.eval(fs.readFileSync(p,'utf8'));
 W.eval(fs.readFileSync('dist/app.js','utf8').replace('W[OWNER]={dispose};','W[OWNER]={dispose};W.test={dbReady,dbOp,s,cfg,PARAMS,pages,normalizeMetadata,metadataVibes,buildRequest,importMetadataVibes,snapshotVibes,cancelAllVibes,updateMetadataEntry,showMetadata,applyCorners,dispose};'));
 const t=W.test;await t.dbReady;assert.equal((await t.dbOp('images','get','retained')).id,'retained');assert(t.pages['元数据库']);assert(!t.pages['文生图配置']);
 const fixture={Source:'NovelAI Diffusion V4.5 4BDE2A90',Comment:JSON.stringify({prompt:'garden',reference_image_multiple:['YWJjZA=='],reference_strength_multiple:[.6],reference_information_extracted_multiple:[1],model_name:'NovelAI Diffusion V4.5'})};
 const metadata=t.normalizeMetadata(fixture),v=t.metadataVibes(fixture);assert.equal(metadata.settings.model,'nai-diffusion-4-5-full');assert.equal(v.items.length,1);v.items[0].selected=true;const req=t.buildRequest({...t.PARAMS,...metadata.settings},metadata,{positive:'',negative:''},v.items,true);assert.equal(req.parameters.reference_image_multiple[0],'YWJjZA==');
 await t.importMetadataVibes(v.items,false);assert.equal((await t.dbOp('vibes','getAll')).length,0);assert.equal(t.snapshotVibes().filter(v=>v.selected).length,1);
 const v5=t.buildRequest({...t.PARAMS,model:'nai-diffusion-5-full'},{prompt:'garden',characters:[]},{positive:'',negative:''},v.items,true);assert(!v5.parameters.reference_image_multiple);await t.cancelAllVibes();assert.equal(t.snapshotVibes().filter(v=>v.selected).length,0);
 await t.dbOp('metadata','put',{id:'m',name:'original',time:1,data:metadata,tags:[],favorite:false});await t.updateMetadataEntry('m',{name:'new name',tags:['light'],favorite:true});const saved=await t.dbOp('metadata','get','m');assert.equal(saved.name,'new name');assert.equal(saved.favorite,true);assert(t.pages['元数据库'].textContent.includes('new name'));assert.equal((await t.dbOp('vibes','getAll')).length,0);
 t.cfg.pair='quality';t.showMetadata({...metadata,warnings:[],vibes:v.items});const shadow=W.document.querySelector('#pear-nai-host').shadowRoot;[...shadow.querySelectorAll('button')].find(x=>x.textContent==='导入选中内容').click();await new Promise(r=>setTimeout(r,20));assert.equal(t.cfg.pair,'none');assert.equal(t.pages['绘图'].hidden,false);assert.equal((await t.dbOp('vibes','getAll')).length,0);
 t.s.ui.cornerStyle='round';t.applyCorners();assert.equal(W.document.querySelector('#pear-nai-host').dataset.corners,'round');
 if(process.env.PEAR_ORIGINALS)for(let i=0;i<3;i++){const raw=JSON.parse(fs.readFileSync(process.env.PEAR_ORIGINALS+'/'+i+'.json')),data=t.normalizeMetadata(raw),parsed=t.metadataVibes(raw);assert.equal(parsed.items.length,[1,4,0][i]);if(i<2){parsed.items.forEach(v=>v.selected=true);const request=t.buildRequest({...t.PARAMS,...data.settings},data,{positive:'',negative:''},parsed.items,true);assert.deepEqual(Array.from(request.parameters.reference_image_multiple),JSON.parse(raw.Comment).reference_image_multiple);}else assert.equal(data.settings.model,'nai-diffusion-5-full');}
 t.dispose();dom.window.close();console.log('PASS standalone: startup, v2 migration, Vibe models, no automatic library writes, V5 cancellation, metadata edits/import/navigation, corners, original PNG fixtures');
})().catch(e=>{console.error(e);process.exit(1)});
