import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const window={};vm.runInNewContext(readFileSync(new URL('../dist/settings-backup.js',import.meta.url),'utf8'),{window,URL});
const B=window.PearSettingsBackup;
const p={id:'api',kind:'api',name:'test',type:'official',url:'https://image.novelai.net',key:'test-only'};
const s={draw:{model:'nai-diffusion-4-5-full',prompt:'garden',negative:'',characters:[]},inline:{model:'nai-diffusion-4-5-full'},pairs:[],ui:{css:null,theme:'tavern'},activeApi:'api',paramSets:[],skins:[],albums:[{id:'keep'}],deletedImages:['keep-deleted']};
const clean=B.create(s,[p]);assert.equal(clean.profiles[0].key,undefined);
assert.equal(B.merge(B.parse(JSON.stringify(clean)),s,[p]).profiles[0].key,p.key);
const withKey=B.create(s,[p],{keys:true,vibes:[{id:'v',name:'vibe'},{id:'g',name:'group',memberIds:['v']}]});
assert.equal(B.parse(JSON.stringify(withKey)).profiles[0].key,p.key);
clean.profiles[0].url='https://other.test';clean.profiles[0].type='third';
assert.equal(B.merge(clean,s,[p]).profiles[0].key,'');
assert.equal(B.merge(withKey,s,[p]).settings.albums[0].id,'keep');
assert.equal(B.merge(withKey,s,[p]).settings.deletedImages[0],'keep-deleted');
assert.throws(()=>B.parse('{"__proto__":{}}'));
assert.throws(()=>B.parse(JSON.stringify({...withKey,version:2})));
assert.throws(()=>B.parse(JSON.stringify({...withKey,vibes:[{id:'g',name:'g',memberIds:['missing']}]})));
console.log('PASS: settings round-trip, key opt-in, endpoint matching, gallery state preservation, malformed backups');
